name: Deploy Docusaurus to GitHub Pages

# Make sure the Pages API is writable:
permissions:
  contents: read        # allows checkout
  pages: write          # allows gh-pages branch updates
  id-token: write       # only needed if you’re doing OIDC

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0         # full history so gh-pages can force-push
          persist-credentials: true  # keep the GITHUB_TOKEN for pushes

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # automatically provided
          USE_SSH: true
        run: npm run deploy
