name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0         # full history so gh-pages can force-push

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build

      # Upload the build folder as a Pages artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build

      # Deploy to GitHub Pages
      - uses: actions/deploy-pages@v1
